<?php 

echo '<?xml version="1.0"?>
<LightMusic><new_details>&lt;p&gt;&#xD;
	With Acoustic versions of songs gaining popularity among musicians and the masses alike, Saarang 2012 brings to you a brand new event - Light Music Acoustics. Soothe the audience and judges with the melody synonymous with Indian Music. With no electronic instruments allowed, for the very first time, we invite bands to go &amp;lsquo;Unplugged&amp;rsquo; !&lt;/p&gt;&#xD;
&lt;p&gt;&#xD;
	&amp;nbsp;&lt;/p&gt;&#xD;
&lt;p&gt;&#xD;
	&amp;nbsp;&lt;/p&gt;&#xD;
</new_details><new_rules>&lt;p&gt;&#xD;
	&lt;strong&gt;PRELIMS: &lt;/strong&gt;&lt;/p&gt;&#xD;
&lt;ol&gt;&#xD;
	&lt;li&gt;&#xD;
		Maximum number of members in a band is 8.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Each band will be allotted 8 minutes (empty stage to empty stage) for both performance and setup.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Participants may perform in any Indian Language (a refrain/rap in English can be used).&amp;nbsp;&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		No electric instruments except for bass guitars will be allowed.&amp;nbsp;&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Mics will be provided for all acoustic instruments.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Keyboards can be used only when set to the piano patch.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		A standard right handed 5 piece drum kit, mics, cables, and amplifiers will be provided. All other instruments must be brought by the&amp;nbsp;bands themselves&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Atleast 2 different instruments must be used.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Purely instrumental pieces are not allowed.One vocalist is compulsory.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		One person cannot participate in more than one band in the same event.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Registration is compulsory.&amp;nbsp;A Saarang ID is mandatory for anyone to participate in this event.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Registrations will start at the hospitality desk ONE HOUR prior to the beginning of the event. Registration will be strictly on first come first serve basis.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		A valid college ID card is necessary for registration.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		&lt;div&gt;&#xD;
			Judges&amp;rsquo; and coordinators&amp;rsquo; decisions shall be final and binding. There shall be no&amp;nbsp;&lt;/div&gt;&#xD;
		&lt;div&gt;&#xD;
			arguments in this regard.&amp;nbsp;&lt;/div&gt;&#xD;
	&lt;/li&gt;&#xD;
&lt;/ol&gt;&#xD;
&lt;p&gt;&#xD;
	&lt;strong&gt;FINALS&lt;/strong&gt;:&lt;/p&gt;&#xD;
&lt;ol&gt;&#xD;
	&lt;li&gt;&#xD;
		Top 6&amp;nbsp;bands from the prelims will be selected for the finals.&amp;nbsp;Only the selected bands from the prelims will be allowed to perform in the final round.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		Each band will be allotted 15 minutes (empty stage to empty stage) for both performance and setup.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		The rest of the rules remain the same as the prelims.&lt;/li&gt;&#xD;
	&lt;li&gt;&#xD;
		&lt;div&gt;&#xD;
			Judges&amp;rsquo; and coordinators&amp;rsquo; decisions shall be final and binding. There shall be no&amp;nbsp;&lt;/div&gt;&#xD;
		&lt;div&gt;&#xD;
			arguments in this regard.&amp;nbsp;&lt;/div&gt;&#xD;
	&lt;/li&gt;&#xD;
&lt;/ol&gt;&#xD;
</new_rules><contact>&lt;div&gt;&#xD;
	For any queries feel free to contact:&amp;nbsp;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	&amp;nbsp;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	Email: &lt;a href=\"\\\"&gt;lm@saarang.org&lt;/a&gt;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	&amp;nbsp;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	Coordinators:&amp;nbsp;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	&amp;bull; Swarun Krishna &amp;nbsp;(+91- 98407 43747)&amp;nbsp;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	&amp;bull; Raunaq Banga &amp;nbsp; (+91- 72004 95724)&amp;nbsp;&lt;/div&gt;&#xD;
&lt;div&gt;&#xD;
	&amp;bull; Sowmya V &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;(+91- 97899 57325)&lt;/div&gt;</contact></LightMusic>
'; ?>